name: idealista
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.0
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  geolocator: ^13.0.2
  get: ^4.6.6
  google_maps_flutter: ^2.10.0
  http_parser: ^4.0.2
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  otp_text_field: ^1.1.3
  shared_preferences: ^2.3.3
flutter_localizations:
    sdk: flutter
    intl: ^0.19.0


  
    cupertino_icons: ^1.0.8 
    google_fonts: ^6.2.1 
    geolocator: ^13.0.2 
    get: ^4.6.5
    google_maps_flutter: ^2.10.0 
    google_places_flutter: ^2.0.9 
    google_maps_polyline: ^1.0.3 
    geocoding: ^3.0.0 
    carousel_slider: ^5.0.0 
    video_player: ^2.9.2 
    http: ^1.2.2 
    photo_view: ^0.15.0 
    chewie: ^1.8.5 
    firebase_auth: ^5.3.3 
    firebase_core: ^3.8.0
    google_sign_in: ^6.2.2 
    flutter_facebook_auth: ^7.1.1 
    permission_handler: ^11.3.1 
    flutter_launcher_icons: ^0.14.1 
    flutter_svg: ^2.0.15
    connectivity_plus: ^2.3.0 
    otp_text_field: ^1.1.3
    image_picker: ^1.1.2
    image_cropper: ^8.0.2
    
dev_dependencies:
    flutter_test:
      sdk: flutter
  
  

    flutter_lints: ^2.0.0

flutter_icons:
          android: true
          ios: true
          image_path: "assets/images/flag.png"

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/l10n/
  
  

 

  # fonts:
  #   - family: VastShadow
  #     fonts:
  #       - asset: font/VastShadow-Regular.ttf
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Medium.ttf
        - asset: fonts/poppins/Poppins-SemiBold.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
    - family: Gabriela
      fonts:
        - asset: fonts/poppins/Gabriela-Regular.ttf
 
